// ui/tooltip.js splits itself in two on purpose: `parse` turns description
// markup into HTML and touches no DOM and no state, which is what lets it run
// over the whole corpus out here. Its own header has said so since it was
// written; nothing was taking it up on the offer.
//
// That matters more than a usual unit test would, because both description
// files are GENERATED by dev scripts kept outside this repo. A change upstream
// -- a new Status Effect, a stray asterisk, an unclosed emphasis -- lands as
// data, not as code, and would otherwise reach a player's screen as raw markup
// with nothing in between to catch it.
//
// So the corpus sweep at the bottom is the point of this file. The unit cases
// above it exist to say what "parsed correctly" means.

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const ROOT = path.join(import.meta.dirname, '..');

function read(rel) {
    return fs.readFileSync(path.join(ROOT, rel), 'utf8');
}

/* tooltip.js hangs itself off `window` and reads the two description globals
   by name, so all three go into one context.

   As ONE script, not three runs of it. Both data files declare their table
   with a top-level `const`, and a top-level const in a vm script is lexical
   to that script rather than a property of the context -- run separately,
   tooltip.js would find no descriptions and the tables would be unreachable
   from out here. tools/dev-fill-save.js documents the same trap against
   script.js's own top-level `let`s. Concatenated, the three share a scope,
   and the epilogue is what carries the tables back out. */
function load() {

    const sandbox = { console };
    sandbox.window = sandbox;
    vm.createContext(sandbox);

    const seam = String.fromCharCode(10) + ';' + String.fromCharCode(10);

    vm.runInContext([
        read('data/descriptions.js'),
        read('data/itemDescriptions.js'),
        read('ui/tooltip.js'),
        'window.__tables = { perks: perkDescriptions, items: itemDescriptions };'
    ].join(seam), sandbox);

    return {
        parse: sandbox.PL.tooltip.parse,
        hasDescription: sandbox.PL.tooltip.hasDescription,
        perks: sandbox.__tables.perks,
        items: sandbox.__tables.items
    };

}

const { parse, hasDescription, perks, items } = load();

/* Every entry in both files, as [name, text]. */
const corpus = Object.entries(perks).concat(Object.entries(items));

/* Tags parse is allowed to emit. Anything else means the escaping let raw
   markup through. */
const ALLOWED = ['b', 'i', 'p', 'ul', 'li', 'span', 'br', 'svg', 'path', 'circle'];

/* Void elements close themselves whether or not they carry a slash, so they
   are counted for what they are and never for whether they balance. parse
   writes its line breaks as a bare <br>, which a naive balance check reads as
   61 unclosed tags across the corpus. */
const VOID = ['br', 'hr', 'img'];

function tagBalance(html) {

    const counts = new Map();
    const re = /<(\/?)([a-zA-Z]+)[^>]*?(\/?)>/g;
    let m;

    while ((m = re.exec(html)) !== null) {

        const [, closing, tag, selfClosing] = m;

        if (!counts.has(tag)) {
            counts.set(tag, 0);
        }

        if (selfClosing || VOID.includes(tag)) {
            continue;
        }

        counts.set(tag, counts.get(tag) + (closing ? -1 : 1));

    }

    return counts;

}

test('the module loads outside a browser at all', () => {

    assert.equal(typeof parse, 'function');
    assert.ok(corpus.length > 250, `expected the full pool, got ${corpus.length}`);

});

test('bold becomes a value, italic becomes flavour', () => {

    assert.match(parse('Gains **50 %** speed.'), /<b class="plTip__v">50 %<\/b>/);
    assert.match(parse('_He was never here._'), /<i class="plTip__i">/);

});

test('a perk naming itself is marked as itself, not merely italic', () => {

    assert.match(parse('_**Dead Hard**_ activates.'), /<i class="plTip__self">/);

});

test('a Status Effect becomes a pill rather than leftover braces', () => {

    const html = parse('You are {Exhausted} for 40 seconds.');

    assert.match(html, /plTip__st/);
    assert.doesNotMatch(html, /[{}]/);

});

test('an unknown Status still loses its braces', () => {

    // Better a plain word than "{Nonsense}" printed at a player.
    const html = parse('You are {Nonsense} now.');

    assert.doesNotMatch(html, /[{}]/);
    assert.match(html, /Nonsense/);

});

test('HTML in the source is escaped, not executed', () => {

    const html = parse('<img src=x onerror=alert(1)> & "quoted"');

    assert.doesNotMatch(html, /<img/);
    assert.match(html, /&lt;img/);
    assert.match(html, /&amp;/);

});

test('empty input is handled without throwing', () => {

    assert.equal(typeof parse(''), 'string');

});

/* ── The corpus sweep ─────────────────────────────────────────────────── */

test('every description parses without leaving markup behind', () => {

    const broken = [];

    for (const [name, text] of corpus) {

        const html = parse(text);

        // A surviving ** or { means the parser did not recognise something the
        // generator emitted, and the player would read the raw mark.
        if (html.includes('**')) {
            broken.push(`${name}: unconsumed ** in output`);
        }

        if (/[{}]/.test(html)) {
            broken.push(`${name}: unconsumed brace in output`);
        }

        if (/\bundefined\b|\bNaN\b/.test(html)) {
            broken.push(`${name}: produced undefined/NaN`);
        }

    }

    assert.deepEqual(broken, [], broken.join('\n'));

});

test('every description produces balanced, expected tags', () => {

    const broken = [];

    for (const [name, text] of corpus) {

        const html = parse(text);

        for (const [tag, depth] of tagBalance(html)) {

            if (!ALLOWED.includes(tag)) {
                broken.push(`${name}: unexpected <${tag}>`);
            }

            if (depth !== 0) {
                broken.push(`${name}: <${tag}> unbalanced by ${depth}`);
            }

        }

    }

    assert.deepEqual(broken, [], broken.join('\n'));

});

test('no description parses to nothing', () => {

    const empty = corpus
        .filter(([, text]) => text.trim() && !parse(text).trim())
        .map(([name]) => name);

    assert.deepEqual(empty, [], `parsed to empty: ${empty.join(', ')}`);

});

test('hasDescription agrees with the corpus it merges', () => {

    for (const [name] of corpus) {
        assert.equal(hasDescription(name), true, `${name} should be described`);
    }

    assert.equal(hasDescription('No Such Perk'), false);

});
